project_id = "plioyqdasznsskgtxglf"

[functions.translate-exam]
verify_jwt = true

[functions.send-exam-notification]
verify_jwt = true

[functions.send-result-notification]
verify_jwt = true

[functions.ocr-extract-text]
verify_jwt = false

[functions.process-book-ocr]
verify_jwt = false

[functions.send-admission-notification]
verify_jwt = false
